### ISSUE TITLE
Master broken: apiserver does not start

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#514]
The mesos/docker apiserver container fails to start: https://teamcity.mesosphere.io/viewLog.html?buildId=51885&buildTypeId=Oss_KubernetesMesos_e2eTests&tab=buildResultsDiv

```
Hostname: apiserver (172.17.0.38)
Waiting (up to 60s) for http://etcd:4001/health to be healthy
Health check of http://etcd:4001/health succeeded!
Waiting (up to 60s) for http://mesosmaster1:5050/health to be healthy
Health check of http://mesosmaster1:5050/health succeeded!
Waiting (up to 60s) for /var/run/kubernetes/auth/apiserver.crt to exist
File /var/run/kubernetes/auth/apiserver.crt exists now!
W0925 20:45:01.462389      49 server.go:176] Failed to start in resource-only container "/kube-proxy": mkdir /sys/fs/cgroup/freezer/kube-proxy: read-only file system
W0925 20:45:01.462489      49 server.go:185] Neither --kubeconfig nor --master was specified.  Using default API client.  This might not work.
W0925 20:45:01.464414      49 iptables.go:140] Error checking iptables version, assuming version at least 1.4.11: exec: "iptables": executable file not found in $PATH
E0925 20:45:01.465237      49 server.go:331] Not trying iptables proxy: can't get Node "apiserver": Get http://localhost:8080/api/v1/nodes/apiserver: dial tcp 127.0.0.1:8080: connection refused
F0925 20:45:01.465506      49 server.go:246] Unable to create proxier: failed to initialize iptables: error creating chain "KUBE-PORTALS-CONTAINER": exec: "iptables": executable file not found in $PATH: 
```

**Comment by jdef** [comment]
I don't understand these logs. iptables is used by kube-proxy not apiserver.

**Comment by sttts** [comment]
Am on it. I thought the same. Maybe something is broken. iptables does not look right in the apiserver.

**Comment by sttts** [comment]
Some hyperkube issue with the kube-proxy refactoring, I guess:
```bash
_output/local/bin/darwin/amd64/km apiserver --help
W0928 18:25:17.106609   42433 server.go:176] Failed to start in resource-only container "/kube-proxy": resource-only containers unsupported in this platform
W0928 18:25:17.109158   42433 server.go:185] Neither --kubeconfig nor --master was specified.  Using default API client.  This might not work.
W0928 18:25:17.115064   42433 iptables.go:140] Error checking iptables version, assuming version at least 1.4.11: exec: "iptables": executable file not found in $PATH
E0928 18:25:17.126931   42433 server.go:331] Not trying iptables proxy: can't get Node "goedel.local": Get http://localhost:8080/api/v1/nodes/goedel.local: dial tcp 127.0.0.1:8080: connection refused
F0928 18:25:17.127849   42433 server.go:246] Unable to create proxier: failed to initialize iptables: error creating chain "KUBE-PORTALS-CONTAINER": exec: "iptables": executable file not found in $PATH:
```

**Comment by sttts** [comment]
Broken by:

```
commit 1c25c2cd9954d2985d115e3dc876918222aff7db
Author: gmarek <gmarek@google.com>
Date:   Mon Sep 21 12:05:22 2015 +0200

    Refactor KubeProxy to allow mocking of all moving parts.
```

**Comment by sttts** [comment]
Broken by:
```
commit 1c25c2cd9954d2985d115e3dc876918222aff7db
Author: gmarek <gmarek@google.com>
Date:   Mon Sep 21 12:05:22 2015 +0200

    Refactor KubeProxy to allow mocking of all moving parts.
```

**Comment by sttts** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/14660

**Comment by F21** [comment]
Just ran into this while trying to build the latest docker image of kubernetes-mesos with kubernetes 1.1.0.

**Comment by sttts** [comment]
Yeah, you have to cherry-pick https://github.com/kubernetes/kubernetes/pull/14660. Note that k8s-1.1 is not a release branch of k8sm. We will soon create one, cherry-picking all necessary patches from master.

**Comment by F21** [comment]
I cherry picked kubernetes/kubernetes#14660 onto my own branch of master, but am still seeing the same problem.

**Comment by sttts** [comment]
You merged the PR or only cherry-picked the last commit? The PR has two commits, one for the Mesos km, one for hypercube.

**Comment by F21** [comment]
Cherry picked the last 2 commits. See here: https://github.com/F21/kubernetes/commits/master

**Comment by F21** [comment]
Scratch that. I just realized I built kubernetes/kubernetes rather than F21/kubernetes.

Will rebuild and report back.

**Comment by F21** [comment]
Just rebuilt and can confirm it works!

**Comment by sttts** [comment]
kubernetes/kubernetes#14660 merged. Closing.
